name: "--------- MAIN WORKFLOW ---------"

on: 
  push: 
    branches:
    - main

jobs:
  firstjob:
    name: "--------- First Job Name ---------"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: FIRST MAIN JOB NAME
        run: |
          echo "First Job print hello world ----------"
      - name: Call Reuse1
        uses: ./.github/workflows/actions/reuse1.yml

  secondjob:
    permissions: write-all
    needs: firstjob
    name: "--------- Second Job Name ---------"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Call Reuse2
        uses: ./.github/workflows/actions/reuse2.yml
