name: "--------- MAIN WORKFLOW ---------"

on: 
  push: 
    branches:
    - main

jobs:
  firstjob:
    name: "--------- First Job Name ---------"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: FIRST MAIN JOB NAME
        run: |
          echo "First Job print hello world ----------"

  secondjob:
    needs: firstjob
    runs-on: ubuntu-latest
    name: "--------- Second Job Name ---------"
    steps:
      - name: Call reuse 1
        uses: ./.github/workflows/reuse1.yml
      - name: Call reuse 2
        uses: ./.github/workflows/reuse2.yml
